In [ ]:
!pip install --upgrade openai

In [ ]:
!pip install pandasai

In [ ]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.0/27.0 MB 29.3 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from faiss-cpu) (1.25.2)
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.8.0

In [ ]:
%pip install -qU langchain langchain-openai langchain-community langchain-experimental pandas

In [ ]:
import openai

Cleaning of Dataset using PandasAI library. Reasons for choosing it has following features:


Natural language querying: Ask questions to your data in natural language.
Data visualization: Generate graphs and charts to visualize your data.
Data cleansing: Cleanse datasets by addressing missing values.
Feature generation: Enhance data quality through feature generation.
Data connectors: Connect to various data sources like CSV, XLSX, PostgreSQL, MySQL, BigQuery, Databrick, Snowflake, etc.

In [ ]:
from pandasai import SmartDataframe
from pandasai.llm import OpenAI

In [ ]:
llm = OpenAI(api_token="YOUR_KEY")

In [ ]:
import pandas as pd  # for storing text and embeddings data

In [ ]:
df_1 = pd.read_csv('/content/drive/MyDrive/bicycleAI/Airline ID to.csv')
df_2 = pd.read_csv('/content/drive/MyDrive/bicycleAI/Flight.csv')

In [ ]:
df_2.head()

,airlie_id,flght#,departure_dt,arrival_dt,dep_time,arrivl_time,booking_cd,passngr_nm,seat_no,class,...,pilot,cabin_crew,inflight_ent,meal_option,wifi,window_seat,aisle_seat,emergency_exit_row,number_of_stops,reward_program_member
0,6,2637,2023-06-26 00:11:20,2023-10-30 21:30:16,13:48:45,21:01:47,BQLF,Name_BANUL,SeatTWV,Economy,...,Pilot_EYZH,Crew_DGAL,Yes,Non-Vegetarian,Not Available,True,True,False,2,Yes
1,5,6966,2023-04-27 21:36:15,2023-10-27 13:13:48,14:05:17,09:12:24,BZIL,Name_KANHR,SeatIGS,Economy,...,Pilot_OKTY,Crew_VNDX,No,Vegetarian,Not Available,False,False,False,2,No
2,12,5670,2023-03-31 15:08:52,2023-12-30 10:58:37,12:47:06,22:28:40,BQPB,Name_ECVFX,SeatJUH,Economy,...,Pilot_UQZR,Crew_PKJB,No,Vegan,Available,False,False,True,0,No
3,1,6203,2023-08-04 16:59:58,2023-03-01 18:34:01,02:46:37,10:53:22,BRPJ,Name_UEUYB,SeatUUC,Economy,...,Pilot_OLHE,Crew_AHUN,No,Vegetarian,Not Available,False,True,False,0,Yes
4,8,6134,2023-03-07 01:08:36,2023-03-30 04:51:17,13:46:28,07:10:26,BSDG,Name_CDWZA,SeatLTY,Business,...,Pilot_DJHP,Crew_DZUM,Yes,Non-Vegetarian,Not Available,True,True,False,2,Yes

In [ ]:
df_1.head()

   airlie_id        airline_name
0          1    American Airline
1          2     Delta Air Lines
2          3     United Airlines
3          4  Southwest Airlines
4          5     JetBlue Airways

In [ ]:
sdf = SmartDataframe(df_1, config={"llm": llm})

In [ ]:
cleaning_response_1=sdf.chat("Are there any missing values present in the data?")

In [ ]:
print(cleaning_response_1)

The number of missing values in the data is: 0

In [ ]:
final_df_1=sdf.chat("Rename columns to more intuitive, business-friendly names for easier querying.")

In [ ]:
df_1.head()

   airline_id        airline_name
0           1    American Airline
1           2     Delta Air Lines
2           3     United Airlines
3           4  Southwest Airlines
4           5     JetBlue Airways

In [ ]:
sdf_2= SmartDataframe(df_2,config={"llm": llm} )

In [ ]:
cleaning_response_df_2_1=sdf_2.chat("Are there any missing values present in the data?")
print(cleaning_response_df_2_1)

0

In [ ]:
reponse_note =sdf_2.chat("Identify and correct inconsistencies within each column in the dataset.")

In [ ]:
print(sdf_2.last_code_generated)

None

In [ ]:
sdf_2.chat("Rename columns to more intuitive, business-friendly names for easier querying. keeping all in small letters")

'Columns renamed successfully.'

In [ ]:
df_2.head()

,airline_id,flight_number,departure_datetime,arrival_datetime,departure_time,arrival_time,booking_code,passenger_name,seat_number,class,...,pilot,cabin_crew,inflight_entertainment,meal_option,wifi,window_seat,aisle_seat,emergency_exit_row,number_of_stops,reward_program_member
0,6,2637,2023-06-26 00:11:20,2023-10-30 21:30:16,13:48:45,21:01:47,BQLF,NAME_BANUL,SEATTWV,ECONOMY,...,PILOT_EYZH,CREW_DGAL,YES,NON-VEGETARIAN,NOT AVAILABLE,True,True,False,2,YES
1,5,6966,2023-04-27 21:36:15,2023-10-27 13:13:48,14:05:17,09:12:24,BZIL,NAME_KANHR,SEATIGS,ECONOMY,...,PILOT_OKTY,CREW_VNDX,NO,VEGETARIAN,NOT AVAILABLE,False,False,False,2,NO
2,12,5670,2023-03-31 15:08:52,2023-12-30 10:58:37,12:47:06,22:28:40,BQPB,NAME_ECVFX,SEATJUH,ECONOMY,...,PILOT_UQZR,CREW_PKJB,NO,VEGAN,AVAILABLE,False,False,True,0,NO
3,1,6203,2023-08-04 16:59:58,2023-03-01 18:34:01,02:46:37,10:53:22,BRPJ,NAME_UEUYB,SEATUUC,ECONOMY,...,PILOT_OLHE,CREW_AHUN,NO,VEGETARIAN,NOT AVAILABLE,False,True,False,0,YES
4,8,6134,2023-03-07 01:08:36,2023-03-30 04:51:17,13:46:28,07:10:26,BSDG,NAME_CDWZA,SEATLTY,BUSINESS,...,PILOT_DJHP,CREW_DZUM,YES,NON-VEGETARIAN,NOT AVAILABLE,True,True,False,2,YES

In [ ]:
from langchain_openai import ChatOpenAI

In [ ]:
import os

os.environ["OPENAI_API_KEY"] = "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"

In [ ]:
langchain_llm = ChatOpenAI(model="gpt-4-0125-preview", temperature=0)

In [ ]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_experimental.tools import PythonAstREPLTool

In [ ]:
from langchain_core.output_parsers import StrOutputParser

In [ ]:
from langchain_community.vectorstores import FAISS
from langchain_core.example_selectors import SemanticSimilarityExampleSelector
from langchain_openai import OpenAIEmbeddings

In [ ]:

import sqlite3



# Step 2: Connect to SQLite database
conn = sqlite3.connect('your_database.db')

# Step 3: Define schema and create tables
table_name1 = 'table1'
table_name2 = 'table2'

df_1.to_sql(table_name1, conn, if_exists='replace', index=False)
df_2.to_sql(table_name2, conn, if_exists='replace', index=False)

# Step 4: Commit changes and close connection
conn.commit()
conn.close()

print(f"CSV files have been successfully converted to SQL database 'your_database.db'.")

CSV files have been successfully converted to SQL database 'your_database.db'.

SQL

In [ ]:
from langchain_community.utilities import SQLDatabase


# Provide the correct path to your SQLite database file
db_path = "/content/your_database.db"

# Create a SQLDatabase object from the SQLite database file
db = SQLDatabase.from_uri(f"sqlite:///{db_path}")

print(db)
print(db.get_usable_table_names())
# print(db.get_usable_table_names())
# db.run("SELECT * FROM Artist LIMIT 10;")

<langchain_community.utilities.sql_database.SQLDatabase object at 0x79e03f02caf0>
['table1', 'table2']

In [ ]:
from langchain_community.agent_toolkits import create_sql_agent

agent_executor = create_sql_agent(langchain_llm, db=db, agent_type="openai-tools", verbose=True)

In [ ]:
response=agent_executor.invoke(
    {
        "input": "What is the airline with highest number of flights?"
    }
)

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with ``


table1, table2
Invoking: `sql_db_schema` with `{'table_names': 'table1'}`



CREATE TABLE table1 (
	airline_id INTEGER,
	airline_name TEXT
)

/*
3 rows from table1 table:
airline_id	airline_name
1	American Airline
2	Delta Air Lines
3	United Airlines
*/
Invoking: `sql_db_schema` with `{'table_names': 'table2'}`



CREATE TABLE table2 (
	airline_id INTEGER,
	flight_number INTEGER,
	departure_datetime TEXT,
	arrival_datetime TEXT,
	departure_time TEXT,
	arrival_time TEXT,
	booking_code TEXT,
	passenger_name TEXT,
	seat_number TEXT,
	class TEXT,
	fare REAL,
	extras TEXT,
	loyalty_points INTEGER,
	status TEXT,
	gate TEXT,
	terminal TEXT,
	baggage_claim TEXT,
	duration_hours REAL,
	layovers INTEGER,
	layover_locations TEXT,
	aircraft_type TEXT,
	pilot TEXT,
	cabin_crew TEXT,
	inflight_entertainment TEXT,
	meal_option TEXT,
	wifi TEXT,
	window_seat INTEGER,
	aisle_seat INTEGER,
	emergency_exit_row INTEGER,
	number_of_stops INTEGER,
	reward_program_member TEXT
)

/*
3 rows from table2 table:
airline_id	flight_number	departure_datetime	arrival_datetime	departure_time	arrival_time	booking_code	passenger_name	seat_number	class	fare	extras	loyalty_points	status	gate	terminal	baggage_claim	duration_hours	layovers	layover_locations	aircraft_type	pilot	cabin_crew	inflight_entertainment	meal_option	wifi	window_seat	aisle_seat	emergency_exit_row	number_of_stops	reward_program_member
6	2637	2023-06-26 00:11:20	2023-10-30 21:30:16	13:48:45	21:01:47	BQLF	Name_BANUL	SeatTWV	Economy	436.12	Meal	3649	Cancelled	GateZN	A	ClaimJLO	8.06	1	LOCWFQ	TypeRUH	Pilot_EYZH	Crew_DGAL	Yes	Non-Vegetarian	Not Available	1	1	0	2	Yes
5	6966	2023-04-27 21:36:15	2023-10-27 13:13:48	14:05:17	09:12:24	BZIL	Name_KANHR	SeatIGS	Economy	965.8	No Extras	2598	Pending	GateMH	D	ClaimCLJ	6.68	1	LOCGGR	TypeSRC	Pilot_OKTY	Crew_VNDX	No	Vegetarian	Not Available	0	0	0	2	No
12	5670	2023-03-31 15:08:52	2023-12-30 10:58:37	12:47:06	22:28:40	BQPB	Name_ECVFX	SeatJUH	Economy	329.94	Meal	0	Pending	GateUU	C	ClaimMPS	9.48	1	LOCLXB	TypeLSA	Pilot_UQZR	Crew_PKJB	No	Vegan	Available	0	0	1	0	No
*/
Invoking: `sql_db_query` with `SELECT airline_id, COUNT(*) as flight_count FROM table2 GROUP BY airline_id ORDER BY flight_count DESC LIMIT 1`


[(16, 593)]
Invoking: `sql_db_query` with `SELECT airline_name FROM table1 WHERE airline_id = 16`


[('KLM Royal Dutch Airlines',)]The airline with the highest number of flights is KLM Royal Dutch Airlines.

> Finished chain.

In [ ]:
#fewshot prompting
examples = [
    {"input": "Calculate the average flight delay per airline.",
     "query": "SELECT table1.AirlineName, AVG((strftime('%s', table2.DepartureTime)-strftime('%s', SUBSTR(table2.DepartureDate, 12)))/60 ) AS AverageDelayInMinutes FROM table1 JOIN table2 ON table1.AirlineID = table2.AirlineID GROUP BY table1.AirlineName;"
    },

]

In [ ]:
#using a SemanticSimilarityExampleSelector, which will perform a semantic search using the embeddings and vector store we configure to find the examples most similar to our input
example_selector = SemanticSimilarityExampleSelector.from_examples(
    examples,
    OpenAIEmbeddings(),
    FAISS,
    k=5,
    input_keys=["input"],
)

In [ ]:
# Using FewShotPromptTemplate, which takes our example selector, an example prompt for formatting each example, and a string prefix and suffix to put before and after our formatted examples
from langchain_core.prompts import (
    ChatPromptTemplate,
    FewShotPromptTemplate,
    MessagesPlaceholder,
    PromptTemplate,
    SystemMessagePromptTemplate,
)

system_prefix = """You are an agent designed to interact with a SQL database.
Given an input question, create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer.
Unless the user specifies a specific number of examples they wish to obtain, always limit your query to at most {top_k} results.
You can order the results by a relevant column to return the most interesting examples in the database.
Never query for all the columns from a specific table, only ask for the relevant columns given the question.
You have access to tools for interacting with the database.
Only use the given tools. Only use the information returned by the tools to construct your final answer.
To find the locations visited you can also use Layovers.
You can use your knowledge to actually name the locations from their shortforms.
Use only the  DepartureDate's and ArrivalDate's time part to calculate delays.

You MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.
You MUST always give ouput based on the given database
DO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.

If the question does not seem related to the database, just return "I don't know" as the answer.

Here are some examples of user inputs and their corresponding SQL queries:"""

few_shot_prompt = FewShotPromptTemplate(
    example_selector=example_selector,
    example_prompt=PromptTemplate.from_template(
        "User input: {input}\nSQL query: {query}"
    ),
    input_variables=["input", "dialect", "top_k"],
    prefix=system_prefix,
    suffix="",
)

In [ ]:
#Since our prompt should be a chat prompt with a human message template and an agent_scratchpad MessagesPlaceholder
full_prompt = ChatPromptTemplate.from_messages(
    [
        SystemMessagePromptTemplate(prompt=few_shot_prompt),
        ("human", "{input}"),
        MessagesPlaceholder("agent_scratchpad"),
    ]
)

In [ ]:
# Provide the correct path to your SQLite database file
db_path = "/content/your_database.db"

# Create a SQLDatabase object from the SQLite database file
db = SQLDatabase.from_uri(f"sqlite:///{db_path}")

In [ ]:
agent_llm = create_sql_agent(
    llm=langchain_llm,
    db=db,
    prompt=full_prompt,
    verbose=True,
    agent_type="openai-tools",
)

In [ ]:
def display_chat_history(messages):
    for message in messages:
        print(f"{message['role'].capitalize()}: {message['content']}")

def get_assistant_response(messages):
    # Assuming `agent_llm` is defined elsewhere
    # Find the most recent user input
    user_input = next((message["content"] for message in reversed(messages) if message["role"] == "user"), None)
    if user_input is None:
        return "I'm sorry, I couldn't find your question."

    # Invoke the agent_llm model with the input query
    response = agent_llm.invoke({"input": user_input})

    # Extract and return the recommended airline from the response
    answer = response["output"]

    # Check if the response is the same as the previous one
    if messages and messages[-1]["role"] == "assistant" and messages[-1]["content"] == answer:
        return "I'm sorry, I couldn't find an answer to that."

    return answer

messages = [{"role": "assistant", "content": "How can I help?"}]

while True:
    display_chat_history(messages)

    user_input = input("User: ")
    messages.append({"role": "user", "content": user_input})  # Append user input as a dictionary

    assistant_response = get_assistant_response(messages)
    messages.append({"role": "assistant", "content": assistant_response})

Assistant: How can I help?


> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


table1, table2
Invoking: `sql_db_schema` with `{'table_names': 'Bookings,Airlines'}`


Error: table_names {'Bookings', 'Airlines'} not found in database
Invoking: `sql_db_list_tables` with `{}`


table1, table2
Invoking: `sql_db_schema` with `{'table_names': 'table1, table2'}`



CREATE TABLE table1 (
	airline_id INTEGER,
	airline_name TEXT
)

/*
3 rows from table1 table:
airline_id	airline_name
1	American Airline
2	Delta Air Lines
3	United Airlines
*/


CREATE TABLE table2 (
	airline_id INTEGER,
	flight_number INTEGER,
	departure_datetime TEXT,
	arrival_datetime TEXT,
	departure_time TEXT,
	arrival_time TEXT,
	booking_code TEXT,
	passenger_name TEXT,
	seat_number TEXT,
	class TEXT,
	fare REAL,
	extras TEXT,
	loyalty_points INTEGER,
	status TEXT,
	gate TEXT,
	terminal TEXT,
	baggage_claim TEXT,
	duration_hours REAL,
	layovers INTEGER,
	layover_locations TEXT,
	aircraft_type TEXT,
	pilot TEXT,
	cabin_crew TEXT,
	inflight_entertainment TEXT,
	meal_option TEXT,
	wifi TEXT,
	window_seat INTEGER,
	aisle_seat INTEGER,
	emergency_exit_row INTEGER,
	number_of_stops INTEGER,
	reward_program_member TEXT
)

/*
3 rows from table2 table:
airline_id	flight_number	departure_datetime	arrival_datetime	departure_time	arrival_time	booking_code	passenger_name	seat_number	class	fare	extras	loyalty_points	status	gate	terminal	baggage_claim	duration_hours	layovers	layover_locations	aircraft_type	pilot	cabin_crew	inflight_entertainment	meal_option	wifi	window_seat	aisle_seat	emergency_exit_row	number_of_stops	reward_program_member
6	2637	2023-06-26 00:11:20	2023-10-30 21:30:16	13:48:45	21:01:47	BQLF	Name_BANUL	SeatTWV	Economy	436.12	Meal	3649	Cancelled	GateZN	A	ClaimJLO	8.06	1	LOCWFQ	TypeRUH	Pilot_EYZH	Crew_DGAL	Yes	Non-Vegetarian	Not Available	1	1	0	2	Yes
5	6966	2023-04-27 21:36:15	2023-10-27 13:13:48	14:05:17	09:12:24	BZIL	Name_KANHR	SeatIGS	Economy	965.8	No Extras	2598	Pending	GateMH	D	ClaimCLJ	6.68	1	LOCGGR	TypeSRC	Pilot_OKTY	Crew_VNDX	No	Vegetarian	Not Available	0	0	0	2	No
12	5670	2023-03-31 15:08:52	2023-12-30 10:58:37	12:47:06	22:28:40	BQPB	Name_ECVFX	SeatJUH	Economy	329.94	Meal	0	Pending	GateUU	C	ClaimMPS	9.48	1	LOCLXB	TypeLSA	Pilot_UQZR	Crew_PKJB	No	Vegan	Available	0	0	1	0	No
*/
Invoking: `sql_db_query` with `SELECT table1.airline_name, strftime('%w', table2.departure_datetime) AS DayOfWeek, COUNT(*) AS TotalBookings, SUM(CASE WHEN table2.status = 'Cancelled' THEN 1 ELSE 0 END) AS CancelledBookings, (SUM(CASE WHEN table2.status = 'Cancelled' THEN 1 ELSE 0 END) * 1.0 / COUNT(*)) * 100 AS CancellationRate FROM table2 JOIN table1 ON table2.airline_id = table1.airline_id GROUP BY table1.airline_name, DayOfWeek ORDER BY CancellationRate DESC, TotalBookings DESC LIMIT 10`


[('Hawaiian Airlines', '0', 64, 29, 45.3125), ('United Airlines', '6', 89, 40, 44.9438202247191), ('Alaska Airlines', '1', 58, 26, 44.827586206896555), ('Frontier Airlines', '6', 59, 26, 44.06779661016949), ('Qantas', '1', 75, 33, 44.0), ('Alaska Airlines', '6', 73, 32, 43.83561643835616), ('Southwest Airlines', '1', 76, 32, 42.10526315789473), ('Singapore Airlines', '0', 81, 34, 41.9753086419753), ('Air Canada', '1', 67, 28, 41.7910447761194), ('JetBlue Airways', '4', 77, 32, 41.55844155844156)]The analysis of booking cancellations reveals specific patterns related to days of the week and airlines with unusually high cancellation rates. Here are the top patterns identified:

1. **Hawaiian Airlines** on **Sunday** (Day 0) has a cancellation rate of **45.31%** with 29 cancellations out of 64 total bookings.
2. **United Airlines** on **Saturday** (Day 6) has a cancellation rate of **44.94%** with 40 cancellations out of 89 total bookings.
3. **Alaska Airlines** on **Monday** (Day 1) has a cancellation rate of **44.83%** with 26 cancellations out of 58 total bookings.
4. **Frontier Airlines** on **Saturday** (Day 6) has a cancellation rate of **44.07%** with 26 cancellations out of 59 total bookings.
5. **Qantas** on **Monday** (Day 1) has a cancellation rate of **44.00%** with 33 cancellations out of 75 total bookings.
6. **Alaska Airlines** on **Saturday** (Day 6) has a cancellation rate of **43.84%** with 32 cancellations out of 73 total bookings.
7. **Southwest Airlines** on **Monday** (Day 1) has a cancellation rate of **42.11%** with 32 cancellations out of 76 total bookings.
8. **Singapore Airlines** on **Sunday** (Day 0) has a cancellation rate of **41.98%** with 34 cancellations out of 81 total bookings.
9. **Air Canada** on **Monday** (Day 1) has a cancellation rate of **41.79%** with 28 cancellations out of 67 total bookings.
10. **JetBlue Airways** on **Thursday** (Day 4) has a cancellation rate of **41.56%** with 32 cancellations out of 77 total bookings.

These results indicate that cancellations are notably high on Sundays and Mondays across various airlines, with Hawaiian Airlines, United Airlines, and Alaska Airlines showing particularly high cancellation rates on these days.

> Finished chain.
Assistant: How can I help?
User: Identify patterns in booking cancellations. Are there specific days or airlines with unusually high cancellation rates?
Assistant: The analysis of booking cancellations reveals specific patterns related to days of the week and airlines with unusually high cancellation rates. Here are the top patterns identified:

1. **Hawaiian Airlines** on **Sunday** (Day 0) has a cancellation rate of **45.31%** with 29 cancellations out of 64 total bookings.
2. **United Airlines** on **Saturday** (Day 6) has a cancellation rate of **44.94%** with 40 cancellations out of 89 total bookings.
3. **Alaska Airlines** on **Monday** (Day 1) has a cancellation rate of **44.83%** with 26 cancellations out of 58 total bookings.
4. **Frontier Airlines** on **Saturday** (Day 6) has a cancellation rate of **44.07%** with 26 cancellations out of 59 total bookings.
5. **Qantas** on **Monday** (Day 1) has a cancellation rate of **44.00%** with 33 cancellations out of 75 total bookings.
6. **Alaska Airlines** on **Saturday** (Day 6) has a cancellation rate of **43.84%** with 32 cancellations out of 73 total bookings.
7. **Southwest Airlines** on **Monday** (Day 1) has a cancellation rate of **42.11%** with 32 cancellations out of 76 total bookings.
8. **Singapore Airlines** on **Sunday** (Day 0) has a cancellation rate of **41.98%** with 34 cancellations out of 81 total bookings.
9. **Air Canada** on **Monday** (Day 1) has a cancellation rate of **41.79%** with 28 cancellations out of 67 total bookings.
10. **JetBlue Airways** on **Thursday** (Day 4) has a cancellation rate of **41.56%** with 32 cancellations out of 77 total bookings.

These results indicate that cancellations are notably high on Sundays and Mondays across various airlines, with Hawaiian Airlines, United Airlines, and Alaska Airlines showing particularly high cancellation rates on these days.


> Entering new SQL Agent Executor chain...

Invoking: `sql_db_query` with `SELECT strftime('%m', BookingDate) AS Month, COUNT(*) AS TotalBookings FROM Bookings GROUP BY Month ORDER BY TotalBookings DESC LIMIT 1`


Error: (sqlite3.OperationalError) no such table: Bookings
[SQL: SELECT strftime('%m', BookingDate) AS Month, COUNT(*) AS TotalBookings FROM Bookings GROUP BY Month ORDER BY TotalBookings DESC LIMIT 1]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Invoking: `sql_db_list_tables` with ``


table1, table2
Invoking: `sql_db_schema` with `{'table_names': 'table1, table2'}`



CREATE TABLE table1 (
	airline_id INTEGER,
	airline_name TEXT
)

/*
3 rows from table1 table:
airline_id	airline_name
1	American Airline
2	Delta Air Lines
3	United Airlines
*/


CREATE TABLE table2 (
	airline_id INTEGER,
	flight_number INTEGER,
	departure_datetime TEXT,
	arrival_datetime TEXT,
	departure_time TEXT,
	arrival_time TEXT,
	booking_code TEXT,
	passenger_name TEXT,
	seat_number TEXT,
	class TEXT,
	fare REAL,
	extras TEXT,
	loyalty_points INTEGER,
	status TEXT,
	gate TEXT,
	terminal TEXT,
	baggage_claim TEXT,
	duration_hours REAL,
	layovers INTEGER,
	layover_locations TEXT,
	aircraft_type TEXT,
	pilot TEXT,
	cabin_crew TEXT,
	inflight_entertainment TEXT,
	meal_option TEXT,
	wifi TEXT,
	window_seat INTEGER,
	aisle_seat INTEGER,
	emergency_exit_row INTEGER,
	number_of_stops INTEGER,
	reward_program_member TEXT
)

/*
3 rows from table2 table:
airline_id	flight_number	departure_datetime	arrival_datetime	departure_time	arrival_time	booking_code	passenger_name	seat_number	class	fare	extras	loyalty_points	status	gate	terminal	baggage_claim	duration_hours	layovers	layover_locations	aircraft_type	pilot	cabin_crew	inflight_entertainment	meal_option	wifi	window_seat	aisle_seat	emergency_exit_row	number_of_stops	reward_program_member
6	2637	2023-06-26 00:11:20	2023-10-30 21:30:16	13:48:45	21:01:47	BQLF	Name_BANUL	SeatTWV	Economy	436.12	Meal	3649	Cancelled	GateZN	A	ClaimJLO	8.06	1	LOCWFQ	TypeRUH	Pilot_EYZH	Crew_DGAL	Yes	Non-Vegetarian	Not Available	1	1	0	2	Yes
5	6966	2023-04-27 21:36:15	2023-10-27 13:13:48	14:05:17	09:12:24	BZIL	Name_KANHR	SeatIGS	Economy	965.8	No Extras	2598	Pending	GateMH	D	ClaimCLJ	6.68	1	LOCGGR	TypeSRC	Pilot_OKTY	Crew_VNDX	No	Vegetarian	Not Available	0	0	0	2	No
12	5670	2023-03-31 15:08:52	2023-12-30 10:58:37	12:47:06	22:28:40	BQPB	Name_ECVFX	SeatJUH	Economy	329.94	Meal	0	Pending	GateUU	C	ClaimMPS	9.48	1	LOCLXB	TypeLSA	Pilot_UQZR	Crew_PKJB	No	Vegan	Available	0	0	1	0	No
*/
Invoking: `sql_db_query` with `SELECT strftime('%m', departure_datetime) AS Month, COUNT(*) AS TotalBookings FROM table2 GROUP BY Month ORDER BY TotalBookings DESC LIMIT 1`


[('10', 906)]The month that observed the highest number of bookings was October.

> Finished chain.
Assistant: How can I help?
User: Identify patterns in booking cancellations. Are there specific days or airlines with unusually high cancellation rates?
Assistant: The analysis of booking cancellations reveals specific patterns related to days of the week and airlines with unusually high cancellation rates. Here are the top patterns identified:

1. **Hawaiian Airlines** on **Sunday** (Day 0) has a cancellation rate of **45.31%** with 29 cancellations out of 64 total bookings.
2. **United Airlines** on **Saturday** (Day 6) has a cancellation rate of **44.94%** with 40 cancellations out of 89 total bookings.
3. **Alaska Airlines** on **Monday** (Day 1) has a cancellation rate of **44.83%** with 26 cancellations out of 58 total bookings.
4. **Frontier Airlines** on **Saturday** (Day 6) has a cancellation rate of **44.07%** with 26 cancellations out of 59 total bookings.
5. **Qantas** on **Monday** (Day 1) has a cancellation rate of **44.00%** with 33 cancellations out of 75 total bookings.
6. **Alaska Airlines** on **Saturday** (Day 6) has a cancellation rate of **43.84%** with 32 cancellations out of 73 total bookings.
7. **Southwest Airlines** on **Monday** (Day 1) has a cancellation rate of **42.11%** with 32 cancellations out of 76 total bookings.
8. **Singapore Airlines** on **Sunday** (Day 0) has a cancellation rate of **41.98%** with 34 cancellations out of 81 total bookings.
9. **Air Canada** on **Monday** (Day 1) has a cancellation rate of **41.79%** with 28 cancellations out of 67 total bookings.
10. **JetBlue Airways** on **Thursday** (Day 4) has a cancellation rate of **41.56%** with 32 cancellations out of 77 total bookings.

These results indicate that cancellations are notably high on Sundays and Mondays across various airlines, with Hawaiian Airlines, United Airlines, and Alaska Airlines showing particularly high cancellation rates on these days.
User: Which month observed the highest number of bookings?
Assistant: The month that observed the highest number of bookings was October.

Identify patterns in booking cancellations. Are there specific days or airlines with unusually high cancellation rates?

In [ ]:
def display_chat_history(messages):
    for message in messages:
        print(f"{message['role'].capitalize()}: {message['content']}")

In [ ]:
def get_assistant_response(messages):
    # Invoke the agent_llm model with the input query
    response = agent_llm.invoke({"input": messages})

    # Extract and return the recommended airline from the response
    answer = response["output"]
    return answer
# def get_assistant_response(messages):
#     r = client.chat.completions.create(
#         model="gpt-3.5-turbo",
#         messages=[{"role": m["role"], "content": m["content"]} for m in messages],
#     )
#     response = r.choices[0].message.content
#     return response

In [ ]:
messages = [{"role": "assistant", "content": "How can I help?"}]

In [ ]:
while True:
    display_chat_history(messages)

    user_input = input("User: ")
    messages.append(user_input)

    assistant_response = get_assistant_response(messages)
    messages.append({"role": "assistant", "content": assistant_response})

Assistant: How can I help?

TypeError: string indices must be integers

In [ ]:
gr.ChatInterface(recomm).launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://5737eae33b042d0567.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)

In [ ]:
agent_llm.invoke(
    {
        "input": "If someone wants to reach his or her destination as soon as possible, which airline would be recommended?"
    }
)

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with ``


table1, table2
Invoking: `sql_db_schema` with `{'table_names': 'table1,table2'}`



CREATE TABLE table1 (
	"AirlineID" INTEGER,
	"AirlineName" TEXT
)

/*
3 rows from table1 table:
AirlineID	AirlineName
1	American Airline
2	Delta Air Lines
3	United Airlines
*/


CREATE TABLE table2 (
	"AirlineID" INTEGER,
	"FlightNumber" INTEGER,
	"DepartureDate" TEXT,
	"ArrivalDate" TEXT,
	"DepartureTime" TEXT,
	"ArrivalTime" TEXT,
	"BookingCode" TEXT,
	"PassengerName" TEXT,
	"SeatNumber" TEXT,
	"Class" TEXT,
	"Fare" REAL,
	"Extras" TEXT,
	"LoyaltyPoints" INTEGER,
	"Status" TEXT,
	"Gate" TEXT,
	"Terminal" TEXT,
	"BaggageClaim" TEXT,
	"FlightDurationHours" REAL,
	"NumberOfLayovers" INTEGER,
	"LayoverLocations" TEXT,
	"AircraftType" TEXT,
	"PilotName" TEXT,
	"CabinCrewNames" TEXT,
	"InflightEntertainmentAvailable" TEXT,
	"MealOption" TEXT,
	"WiFiAvailable" TEXT,
	"WindowSeatAvailable" INTEGER,
	"AisleSeatAvailable" INTEGER,
	"EmergencyExitRowSeat" INTEGER,
	"NumberOfStops" INTEGER,
	"RewardProgramMember" TEXT
)

/*
3 rows from table2 table:
AirlineID	FlightNumber	DepartureDate	ArrivalDate	DepartureTime	ArrivalTime	BookingCode	PassengerName	SeatNumber	Class	Fare	Extras	LoyaltyPoints	Status	Gate	Terminal	BaggageClaim	FlightDurationHours	NumberOfLayovers	LayoverLocations	AircraftType	PilotName	CabinCrewNames	InflightEntertainmentAvailable	MealOption	WiFiAvailable	WindowSeatAvailable	AisleSeatAvailable	EmergencyExitRowSeat	NumberOfStops	RewardProgramMember
6	2637	2023-06-26 00:11:20	2023-10-30 21:30:16	13:48:45	21:01:47	BQLF	Name_BANUL	SeatTWV	Economy	436.12	Meal	3649	Cancelled	GateZN	A	ClaimJLO	8.06	1	LOCWFQ	TypeRUH	Pilot_EYZH	Crew_DGAL	Yes	Non-Vegetarian	Not Available	1	1	0	2	Yes
5	6966	2023-04-27 21:36:15	2023-10-27 13:13:48	14:05:17	09:12:24	BZIL	Name_KANHR	SeatIGS	Economy	965.8	No Extras	2598	Pending	GateMH	D	ClaimCLJ	6.68	1	LOCGGR	TypeSRC	Pilot_OKTY	Crew_VNDX	No	Vegetarian	Not Available	0	0	0	2	No
12	5670	2023-03-31 15:08:52	2023-12-30 10:58:37	12:47:06	22:28:40	BQPB	Name_ECVFX	SeatJUH	Economy	329.94	Meal	0	Pending	GateUU	C	ClaimMPS	9.48	1	LOCLXB	TypeLSA	Pilot_UQZR	Crew_PKJB	No	Vegan	Available	0	0	1	0	No
*/
Invoking: `sql_db_query` with `SELECT table1.AirlineName, AVG(table2.FlightDurationHours) AS AverageFlightDuration FROM table1 JOIN table2 ON table1.AirlineID = table2.AirlineID GROUP BY table1.AirlineName ORDER BY AverageFlightDuration ASC LIMIT 1`


[('British Airways', 6.129412780656305)]The airline recommended for reaching your destination as soon as possible is British Airways, with an average flight duration of approximately 6.13 hours.

> Finished chain.

{'input': 'If someone wants to reach his or her destination as soon as possible, which airline would be recommended?',
 'output': 'The airline recommended for reaching your destination as soon as possible is British Airways, with an average flight duration of approximately 6.13 hours.'}

In [ ]:
!pip install gradio

Collecting gradio
  Downloading gradio-4.21.0-py3-none-any.whl (17.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 13.1 MB/s eta 0:00:00
Collecting aiofiles<24.0,>=22.0 (from gradio)
  Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Requirement already satisfied: altair<6.0,>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (4.2.2)
Collecting fastapi (from gradio)
  Downloading fastapi-0.110.0-py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.1/92.1 kB 3.3 MB/s eta 0:00:00
Collecting ffmpy (from gradio)
  Downloading ffmpy-0.3.2.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... done
Collecting gradio-client==0.12.0 (from gradio)
  Downloading gradio_client-0.12.0-py3-none-any.whl (310 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.7/310.7 kB 23.3 MB/s eta 0:00:00
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.27.0)
Requirement already satisfied: huggingface-hub>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.20.3)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in /usr/local/lib/python3.10/dist-packages (from gradio) (6.3.0)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.1.3)
Requirement already satisfied: markupsafe~=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.1.5)
Requirement already satisfied: matplotlib~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.7.1)
Requirement already satisfied: numpy~=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (1.25.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.9.15)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gradio) (23.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.2.1)
Requirement already satisfied: pillow<11.0,>=8.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (9.4.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.6.4)
Collecting pydub (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting python-multipart>=0.0.9 (from gradio)
  Downloading python_multipart-0.0.9-py3-none-any.whl (22 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (6.0.1)
Collecting ruff>=0.2.2 (from gradio)
  Downloading ruff-0.3.3-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 46.3 MB/s eta 0:00:00
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting tomlkit==0.12.0 (from gradio)
  Downloading tomlkit-0.12.0-py3-none-any.whl (37 kB)
Requirement already satisfied: typer[all]<1.0,>=0.9 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.9.0)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (4.10.0)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.28.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from gradio-client==0.12.0->gradio) (2023.6.0)
Collecting websockets<12.0,>=10.0 (from gradio-client==0.12.0->gradio)
  Downloading websockets-11.0.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 12.0 MB/s eta 0:00:00
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6.0,>=4.2.0->gradio) (0.4)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6.0,>=4.2.0->gradio) (4.19.2)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6.0,>=4.2.0->gradio) (0.12.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (2024.2.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (1.0.4)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (3.6)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.3->gradio) (3.13.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.3->gradio) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.3->gradio) (4.66.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib~=3.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.1)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (2.16.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer[all]<1.0,>=0.9->gradio) (8.1.7)
Collecting colorama<0.5.0,>=0.4.3 (from typer[all]<1.0,>=0.9->gradio)
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting shellingham<2.0.0,>=1.3.0 (from typer[all]<1.0,>=0.9->gradio)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Requirement already satisfied: rich<14.0.0,>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer[all]<1.0,>=0.9->gradio) (13.7.1)
Collecting starlette<0.37.0,>=0.36.3 (from fastapi->gradio)
  Downloading starlette-0.36.3-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 6.2 MB/s eta 0:00:00
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio) (0.33.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio) (0.18.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib~=3.0->gradio) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14.0.0,>=10.11.0->typer[all]<1.0,>=0.9->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14.0.0,>=10.11.0->typer[all]<1.0,>=0.9->gradio) (2.16.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx>=0.24.1->gradio) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.19.3->gradio) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.19.3->gradio) (2.0.7)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=10.11.0->typer[all]<1.0,>=0.9->gradio) (0.1.2)
Building wheels for collected packages: ffmpy
  Building wheel for ffmpy (setup.py) ... done
  Created wheel for ffmpy: filename=ffmpy-0.3.2-py3-none-any.whl size=5584 sha256=073f5cabbf6260102486557fbabb5080d0391244b7ebfa381376dab927920fda
  Stored in directory: /root/.cache/pip/wheels/bd/65/9a/671fc6dcde07d4418df0c592f8df512b26d7a0029c2a23dd81
Successfully built ffmpy
Installing collected packages: pydub, ffmpy, websockets, uvicorn, tomlkit, shellingham, semantic-version, ruff, python-multipart, colorama, aiofiles, starlette, gradio-client, fastapi, gradio
Successfully installed aiofiles-23.2.1 colorama-0.4.6 fastapi-0.110.0 ffmpy-0.3.2 gradio-4.21.0 gradio-client-0.12.0 pydub-0.25.1 python-multipart-0.0.9 ruff-0.3.3 semantic-version-2.10.0 shellingham-1.5.4 starlette-0.36.3 tomlkit-0.12.0 uvicorn-0.28.0 websockets-11.0.3

In [ ]:
import gradio as gr